//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/ontai-dev/seam-core/pkg/lineage"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescendantEntry) DeepCopyInto(out *DescendantEntry) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescendantEntry.
func (in *DescendantEntry) DeepCopy() *DescendantEntry {
	if in == nil {
		return nil
	}
	out := new(DescendantEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftAffectedCRRef) DeepCopyInto(out *DriftAffectedCRRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftAffectedCRRef.
func (in *DriftAffectedCRRef) DeepCopy() *DriftAffectedCRRef {
	if in == nil {
		return nil
	}
	out := new(DriftAffectedCRRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSignal) DeepCopyInto(out *DriftSignal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSignal.
func (in *DriftSignal) DeepCopy() *DriftSignal {
	if in == nil {
		return nil
	}
	out := new(DriftSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriftSignal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSignalList) DeepCopyInto(out *DriftSignalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DriftSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSignalList.
func (in *DriftSignalList) DeepCopy() *DriftSignalList {
	if in == nil {
		return nil
	}
	out := new(DriftSignalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriftSignalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSignalSpec) DeepCopyInto(out *DriftSignalSpec) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	out.AffectedCRRef = in.AffectedCRRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSignalSpec.
func (in *DriftSignalSpec) DeepCopy() *DriftSignalSpec {
	if in == nil {
		return nil
	}
	out := new(DriftSignalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSignalStatus) DeepCopyInto(out *DriftSignalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSignalStatus.
func (in *DriftSignalStatus) DeepCopy() *DriftSignalStatus {
	if in == nil {
		return nil
	}
	out := new(DriftSignalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureCAPICiliumPackRef) DeepCopyInto(out *InfrastructureCAPICiliumPackRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureCAPICiliumPackRef.
func (in *InfrastructureCAPICiliumPackRef) DeepCopy() *InfrastructureCAPICiliumPackRef {
	if in == nil {
		return nil
	}
	out := new(InfrastructureCAPICiliumPackRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureCAPIConfig) DeepCopyInto(out *InfrastructureCAPIConfig) {
	*out = *in
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(InfrastructureCAPIControlPlaneConfig)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]InfrastructureCAPIWorkerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CiliumPackRef != nil {
		in, out := &in.CiliumPackRef, &out.CiliumPackRef
		*out = new(InfrastructureCAPICiliumPackRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureCAPIConfig.
func (in *InfrastructureCAPIConfig) DeepCopy() *InfrastructureCAPIConfig {
	if in == nil {
		return nil
	}
	out := new(InfrastructureCAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureCAPIControlPlaneConfig) DeepCopyInto(out *InfrastructureCAPIControlPlaneConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureCAPIControlPlaneConfig.
func (in *InfrastructureCAPIControlPlaneConfig) DeepCopy() *InfrastructureCAPIControlPlaneConfig {
	if in == nil {
		return nil
	}
	out := new(InfrastructureCAPIControlPlaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureCAPIWorkerPool) DeepCopyInto(out *InfrastructureCAPIWorkerPool) {
	*out = *in
	if in.SeamInfrastructureMachineNames != nil {
		in, out := &in.SeamInfrastructureMachineNames, &out.SeamInfrastructureMachineNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureCAPIWorkerPool.
func (in *InfrastructureCAPIWorkerPool) DeepCopy() *InfrastructureCAPIWorkerPool {
	if in == nil {
		return nil
	}
	out := new(InfrastructureCAPIWorkerPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureClusterPack) DeepCopyInto(out *InfrastructureClusterPack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureClusterPack.
func (in *InfrastructureClusterPack) DeepCopy() *InfrastructureClusterPack {
	if in == nil {
		return nil
	}
	out := new(InfrastructureClusterPack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureClusterPack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureClusterPackList) DeepCopyInto(out *InfrastructureClusterPackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructureClusterPack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureClusterPackList.
func (in *InfrastructureClusterPackList) DeepCopy() *InfrastructureClusterPackList {
	if in == nil {
		return nil
	}
	out := new(InfrastructureClusterPackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureClusterPackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureClusterPackRef) DeepCopyInto(out *InfrastructureClusterPackRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureClusterPackRef.
func (in *InfrastructureClusterPackRef) DeepCopy() *InfrastructureClusterPackRef {
	if in == nil {
		return nil
	}
	out := new(InfrastructureClusterPackRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureClusterPackSpec) DeepCopyInto(out *InfrastructureClusterPackSpec) {
	*out = *in
	out.RegistryRef = in.RegistryRef
	if in.ExecutionOrder != nil {
		in, out := &in.ExecutionOrder, &out.ExecutionOrder
		*out = make([]InfrastructurePackExecutionStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provenance != nil {
		in, out := &in.Provenance, &out.Provenance
		*out = new(InfrastructurePackProvenance)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetClusters != nil {
		in, out := &in.TargetClusters, &out.TargetClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LifecyclePolicies != nil {
		in, out := &in.LifecyclePolicies, &out.LifecyclePolicies
		*out = new(InfrastructureLifecyclePolicy)
		**out = **in
	}
	if in.Lineage != nil {
		in, out := &in.Lineage, &out.Lineage
		*out = new(lineage.SealedCausalChain)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureClusterPackSpec.
func (in *InfrastructureClusterPackSpec) DeepCopy() *InfrastructureClusterPackSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureClusterPackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureClusterPackStatus) DeepCopyInto(out *InfrastructureClusterPackStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureClusterPackStatus.
func (in *InfrastructureClusterPackStatus) DeepCopy() *InfrastructureClusterPackStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureClusterPackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureDependencyPolicy) DeepCopyInto(out *InfrastructureDependencyPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureDependencyPolicy.
func (in *InfrastructureDependencyPolicy) DeepCopy() *InfrastructureDependencyPolicy {
	if in == nil {
		return nil
	}
	out := new(InfrastructureDependencyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureDeployedResourceRef) DeepCopyInto(out *InfrastructureDeployedResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureDeployedResourceRef.
func (in *InfrastructureDeployedResourceRef) DeepCopy() *InfrastructureDeployedResourceRef {
	if in == nil {
		return nil
	}
	out := new(InfrastructureDeployedResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLifecyclePolicy) DeepCopyInto(out *InfrastructureLifecyclePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLifecyclePolicy.
func (in *InfrastructureLifecyclePolicy) DeepCopy() *InfrastructureLifecyclePolicy {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLifecyclePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndex) DeepCopyInto(out *InfrastructureLineageIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndex.
func (in *InfrastructureLineageIndex) DeepCopy() *InfrastructureLineageIndex {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureLineageIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexList) DeepCopyInto(out *InfrastructureLineageIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructureLineageIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexList.
func (in *InfrastructureLineageIndexList) DeepCopy() *InfrastructureLineageIndexList {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureLineageIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexRootBinding) DeepCopyInto(out *InfrastructureLineageIndexRootBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexRootBinding.
func (in *InfrastructureLineageIndexRootBinding) DeepCopy() *InfrastructureLineageIndexRootBinding {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexRootBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexSpec) DeepCopyInto(out *InfrastructureLineageIndexSpec) {
	*out = *in
	out.RootBinding = in.RootBinding
	if in.DescendantRegistry != nil {
		in, out := &in.DescendantRegistry, &out.DescendantRegistry
		*out = make([]DescendantEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyBindingStatus != nil {
		in, out := &in.PolicyBindingStatus, &out.PolicyBindingStatus
		*out = new(InfrastructurePolicyBindingStatus)
		**out = **in
	}
	if in.OutcomeRegistry != nil {
		in, out := &in.OutcomeRegistry, &out.OutcomeRegistry
		*out = make([]OutcomeEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(LineageRetentionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexSpec.
func (in *InfrastructureLineageIndexSpec) DeepCopy() *InfrastructureLineageIndexSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexStatus) DeepCopyInto(out *InfrastructureLineageIndexStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexStatus.
func (in *InfrastructureLineageIndexStatus) DeepCopy() *InfrastructureLineageIndexStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLocalObjectRef) DeepCopyInto(out *InfrastructureLocalObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLocalObjectRef.
func (in *InfrastructureLocalObjectRef) DeepCopy() *InfrastructureLocalObjectRef {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLocalObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackBuild) DeepCopyInto(out *InfrastructurePackBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackBuild.
func (in *InfrastructurePackBuild) DeepCopy() *InfrastructurePackBuild {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructurePackBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackBuildList) DeepCopyInto(out *InfrastructurePackBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructurePackBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackBuildList.
func (in *InfrastructurePackBuildList) DeepCopy() *InfrastructurePackBuildList {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructurePackBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackBuildSpec) DeepCopyInto(out *InfrastructurePackBuildSpec) {
	*out = *in
	if in.HelmSource != nil {
		in, out := &in.HelmSource, &out.HelmSource
		*out = new(InfrastructurePackHelmSource)
		**out = **in
	}
	if in.KustomizeSource != nil {
		in, out := &in.KustomizeSource, &out.KustomizeSource
		*out = new(InfrastructurePackKustomizeSource)
		**out = **in
	}
	if in.RawSource != nil {
		in, out := &in.RawSource, &out.RawSource
		*out = new(InfrastructurePackRawSource)
		**out = **in
	}
	if in.TargetClusters != nil {
		in, out := &in.TargetClusters, &out.TargetClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackBuildSpec.
func (in *InfrastructurePackBuildSpec) DeepCopy() *InfrastructurePackBuildSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackBuildStatus) DeepCopyInto(out *InfrastructurePackBuildStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackBuildStatus.
func (in *InfrastructurePackBuildStatus) DeepCopy() *InfrastructurePackBuildStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackExecution) DeepCopyInto(out *InfrastructurePackExecution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackExecution.
func (in *InfrastructurePackExecution) DeepCopy() *InfrastructurePackExecution {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructurePackExecution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackExecutionList) DeepCopyInto(out *InfrastructurePackExecutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructurePackExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackExecutionList.
func (in *InfrastructurePackExecutionList) DeepCopy() *InfrastructurePackExecutionList {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackExecutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructurePackExecutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackExecutionSpec) DeepCopyInto(out *InfrastructurePackExecutionSpec) {
	*out = *in
	out.ClusterPackRef = in.ClusterPackRef
	if in.Lineage != nil {
		in, out := &in.Lineage, &out.Lineage
		*out = new(lineage.SealedCausalChain)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackExecutionSpec.
func (in *InfrastructurePackExecutionSpec) DeepCopy() *InfrastructurePackExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackExecutionStage) DeepCopyInto(out *InfrastructurePackExecutionStage) {
	*out = *in
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackExecutionStage.
func (in *InfrastructurePackExecutionStage) DeepCopy() *InfrastructurePackExecutionStage {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackExecutionStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackExecutionStatus) DeepCopyInto(out *InfrastructurePackExecutionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackExecutionStatus.
func (in *InfrastructurePackExecutionStatus) DeepCopy() *InfrastructurePackExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackHelmSource) DeepCopyInto(out *InfrastructurePackHelmSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackHelmSource.
func (in *InfrastructurePackHelmSource) DeepCopy() *InfrastructurePackHelmSource {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackHelmSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackInstance) DeepCopyInto(out *InfrastructurePackInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackInstance.
func (in *InfrastructurePackInstance) DeepCopy() *InfrastructurePackInstance {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructurePackInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackInstanceList) DeepCopyInto(out *InfrastructurePackInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructurePackInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackInstanceList.
func (in *InfrastructurePackInstanceList) DeepCopy() *InfrastructurePackInstanceList {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructurePackInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackInstanceSpec) DeepCopyInto(out *InfrastructurePackInstanceSpec) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DependencyPolicy != nil {
		in, out := &in.DependencyPolicy, &out.DependencyPolicy
		*out = new(InfrastructureDependencyPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackInstanceSpec.
func (in *InfrastructurePackInstanceSpec) DeepCopy() *InfrastructurePackInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackInstanceStatus) DeepCopyInto(out *InfrastructurePackInstanceStatus) {
	*out = *in
	if in.DeliveredAt != nil {
		in, out := &in.DeliveredAt, &out.DeliveredAt
		*out = (*in).DeepCopy()
	}
	if in.DeployedResources != nil {
		in, out := &in.DeployedResources, &out.DeployedResources
		*out = make([]InfrastructureDeployedResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackInstanceStatus.
func (in *InfrastructurePackInstanceStatus) DeepCopy() *InfrastructurePackInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackKustomizeSource) DeepCopyInto(out *InfrastructurePackKustomizeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackKustomizeSource.
func (in *InfrastructurePackKustomizeSource) DeepCopy() *InfrastructurePackKustomizeSource {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackKustomizeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackProvenance) DeepCopyInto(out *InfrastructurePackProvenance) {
	*out = *in
	if in.BuildTimestamp != nil {
		in, out := &in.BuildTimestamp, &out.BuildTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackProvenance.
func (in *InfrastructurePackProvenance) DeepCopy() *InfrastructurePackProvenance {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackRawSource) DeepCopyInto(out *InfrastructurePackRawSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackRawSource.
func (in *InfrastructurePackRawSource) DeepCopy() *InfrastructurePackRawSource {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackRawSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackReceipt) DeepCopyInto(out *InfrastructurePackReceipt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackReceipt.
func (in *InfrastructurePackReceipt) DeepCopy() *InfrastructurePackReceipt {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackReceipt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructurePackReceipt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackReceiptList) DeepCopyInto(out *InfrastructurePackReceiptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructurePackReceipt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackReceiptList.
func (in *InfrastructurePackReceiptList) DeepCopy() *InfrastructurePackReceiptList {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackReceiptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructurePackReceiptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackReceiptSpec) DeepCopyInto(out *InfrastructurePackReceiptSpec) {
	*out = *in
	if in.DeployedResources != nil {
		in, out := &in.DeployedResources, &out.DeployedResources
		*out = make([]PackReceiptDeployedResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackReceiptDeployedResource) DeepCopyInto(out *PackReceiptDeployedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackReceiptDeployedResource.
func (in *PackReceiptDeployedResource) DeepCopy() *PackReceiptDeployedResource {
	if in == nil {
		return nil
	}
	out := new(PackReceiptDeployedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackReceiptSpec.
func (in *InfrastructurePackReceiptSpec) DeepCopy() *InfrastructurePackReceiptSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackReceiptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackReceiptStatus) DeepCopyInto(out *InfrastructurePackReceiptStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackReceiptStatus.
func (in *InfrastructurePackReceiptStatus) DeepCopy() *InfrastructurePackReceiptStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackReceiptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePackRegistryRef) DeepCopyInto(out *InfrastructurePackRegistryRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePackRegistryRef.
func (in *InfrastructurePackRegistryRef) DeepCopy() *InfrastructurePackRegistryRef {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePackRegistryRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePolicyBindingStatus) DeepCopyInto(out *InfrastructurePolicyBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePolicyBindingStatus.
func (in *InfrastructurePolicyBindingStatus) DeepCopy() *InfrastructurePolicyBindingStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePolicyBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureRunnerConfig) DeepCopyInto(out *InfrastructureRunnerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureRunnerConfig.
func (in *InfrastructureRunnerConfig) DeepCopy() *InfrastructureRunnerConfig {
	if in == nil {
		return nil
	}
	out := new(InfrastructureRunnerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureRunnerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureRunnerConfigList) DeepCopyInto(out *InfrastructureRunnerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructureRunnerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureRunnerConfigList.
func (in *InfrastructureRunnerConfigList) DeepCopy() *InfrastructureRunnerConfigList {
	if in == nil {
		return nil
	}
	out := new(InfrastructureRunnerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureRunnerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureRunnerConfigSpec) DeepCopyInto(out *InfrastructureRunnerConfigSpec) {
	*out = *in
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make([]RunnerPhaseConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]RunnerConfigStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OperationalHistory != nil {
		in, out := &in.OperationalHistory, &out.OperationalHistory
		*out = make([]RunnerOperationalHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaintenanceTargetNodes != nil {
		in, out := &in.MaintenanceTargetNodes, &out.MaintenanceTargetNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureRunnerConfigSpec.
func (in *InfrastructureRunnerConfigSpec) DeepCopy() *InfrastructureRunnerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureRunnerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureRunnerConfigStatus) DeepCopyInto(out *InfrastructureRunnerConfigStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]RunnerCapabilityEntry, len(*in))
		copy(*out, *in)
	}
	if in.StepResults != nil {
		in, out := &in.StepResults, &out.StepResults
		*out = make([]RunnerConfigStepResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureRunnerConfigStatus.
func (in *InfrastructureRunnerConfigStatus) DeepCopy() *InfrastructureRunnerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureRunnerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureTalosCluster) DeepCopyInto(out *InfrastructureTalosCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureTalosCluster.
func (in *InfrastructureTalosCluster) DeepCopy() *InfrastructureTalosCluster {
	if in == nil {
		return nil
	}
	out := new(InfrastructureTalosCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureTalosCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureTalosClusterList) DeepCopyInto(out *InfrastructureTalosClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructureTalosCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureTalosClusterList.
func (in *InfrastructureTalosClusterList) DeepCopy() *InfrastructureTalosClusterList {
	if in == nil {
		return nil
	}
	out := new(InfrastructureTalosClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureTalosClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureTalosClusterOperationResult) DeepCopyInto(out *InfrastructureTalosClusterOperationResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureTalosClusterOperationResult.
func (in *InfrastructureTalosClusterOperationResult) DeepCopy() *InfrastructureTalosClusterOperationResult {
	if in == nil {
		return nil
	}
	out := new(InfrastructureTalosClusterOperationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureTalosClusterOperationResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureTalosClusterOperationResultList) DeepCopyInto(out *InfrastructureTalosClusterOperationResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructureTalosClusterOperationResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureTalosClusterOperationResultList.
func (in *InfrastructureTalosClusterOperationResultList) DeepCopy() *InfrastructureTalosClusterOperationResultList {
	if in == nil {
		return nil
	}
	out := new(InfrastructureTalosClusterOperationResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureTalosClusterOperationResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureTalosClusterOperationResultSpec) DeepCopyInto(out *InfrastructureTalosClusterOperationResultSpec) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make(map[string]TalosClusterOperationRecord, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureTalosClusterOperationResultSpec.
func (in *InfrastructureTalosClusterOperationResultSpec) DeepCopy() *InfrastructureTalosClusterOperationResultSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureTalosClusterOperationResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureTalosClusterOperationResultStatus) DeepCopyInto(out *InfrastructureTalosClusterOperationResultStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureTalosClusterOperationResultStatus.
func (in *InfrastructureTalosClusterOperationResultStatus) DeepCopy() *InfrastructureTalosClusterOperationResultStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureTalosClusterOperationResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureTalosClusterSpec) DeepCopyInto(out *InfrastructureTalosClusterSpec) {
	*out = *in
	if in.NodeAddresses != nil {
		in, out := &in.NodeAddresses, &out.NodeAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CAPI != nil {
		in, out := &in.CAPI, &out.CAPI
		*out = new(InfrastructureCAPIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Lineage != nil {
		in, out := &in.Lineage, &out.Lineage
		*out = new(lineage.SealedCausalChain)
		**out = **in
	}
	if in.HardeningProfileRef != nil {
		in, out := &in.HardeningProfileRef, &out.HardeningProfileRef
		*out = new(InfrastructureLocalObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureTalosClusterSpec.
func (in *InfrastructureTalosClusterSpec) DeepCopy() *InfrastructureTalosClusterSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureTalosClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureTalosClusterStatus) DeepCopyInto(out *InfrastructureTalosClusterStatus) {
	*out = *in
	if in.CAPIClusterRef != nil {
		in, out := &in.CAPIClusterRef, &out.CAPIClusterRef
		*out = new(InfrastructureLocalObjectRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PkiExpiryDate != nil {
		in, out := &in.PkiExpiryDate, &out.PkiExpiryDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureTalosClusterStatus.
func (in *InfrastructureTalosClusterStatus) DeepCopy() *InfrastructureTalosClusterStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureTalosClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRetentionPolicy) DeepCopyInto(out *LineageRetentionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRetentionPolicy.
func (in *LineageRetentionPolicy) DeepCopy() *LineageRetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(LineageRetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutcomeEntry) DeepCopyInto(out *OutcomeEntry) {
	*out = *in
	in.OutcomeTimestamp.DeepCopyInto(&out.OutcomeTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutcomeEntry.
func (in *OutcomeEntry) DeepCopy() *OutcomeEntry {
	if in == nil {
		return nil
	}
	out := new(OutcomeEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationArtifact) DeepCopyInto(out *PackOperationArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationArtifact.
func (in *PackOperationArtifact) DeepCopy() *PackOperationArtifact {
	if in == nil {
		return nil
	}
	out := new(PackOperationArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationDeployedResource) DeepCopyInto(out *PackOperationDeployedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationDeployedResource.
func (in *PackOperationDeployedResource) DeepCopy() *PackOperationDeployedResource {
	if in == nil {
		return nil
	}
	out := new(PackOperationDeployedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationFailureReason) DeepCopyInto(out *PackOperationFailureReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationFailureReason.
func (in *PackOperationFailureReason) DeepCopy() *PackOperationFailureReason {
	if in == nil {
		return nil
	}
	out := new(PackOperationFailureReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationResult) DeepCopyInto(out *PackOperationResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationResult.
func (in *PackOperationResult) DeepCopy() *PackOperationResult {
	if in == nil {
		return nil
	}
	out := new(PackOperationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackOperationResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationResultList) DeepCopyInto(out *PackOperationResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PackOperationResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationResultList.
func (in *PackOperationResultList) DeepCopy() *PackOperationResultList {
	if in == nil {
		return nil
	}
	out := new(PackOperationResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackOperationResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationResultSpec) DeepCopyInto(out *PackOperationResultSpec) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(PackOperationFailureReason)
		**out = **in
	}
	if in.DeployedResources != nil {
		in, out := &in.DeployedResources, &out.DeployedResources
		*out = make([]PackOperationDeployedResource, len(*in))
		copy(*out, *in)
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]PackOperationArtifact, len(*in))
		copy(*out, *in)
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]PackOperationStepResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationResultSpec.
func (in *PackOperationResultSpec) DeepCopy() *PackOperationResultSpec {
	if in == nil {
		return nil
	}
	out := new(PackOperationResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationResultStatus) DeepCopyInto(out *PackOperationResultStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationResultStatus.
func (in *PackOperationResultStatus) DeepCopy() *PackOperationResultStatus {
	if in == nil {
		return nil
	}
	out := new(PackOperationResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationStepResult) DeepCopyInto(out *PackOperationStepResult) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationStepResult.
func (in *PackOperationStepResult) DeepCopy() *PackOperationStepResult {
	if in == nil {
		return nil
	}
	out := new(PackOperationStepResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerCapabilityEntry) DeepCopyInto(out *RunnerCapabilityEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerCapabilityEntry.
func (in *RunnerCapabilityEntry) DeepCopy() *RunnerCapabilityEntry {
	if in == nil {
		return nil
	}
	out := new(RunnerCapabilityEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfigStep) DeepCopyInto(out *RunnerConfigStep) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfigStep.
func (in *RunnerConfigStep) DeepCopy() *RunnerConfigStep {
	if in == nil {
		return nil
	}
	out := new(RunnerConfigStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfigStepResult) DeepCopyInto(out *RunnerConfigStepResult) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfigStepResult.
func (in *RunnerConfigStepResult) DeepCopy() *RunnerConfigStepResult {
	if in == nil {
		return nil
	}
	out := new(RunnerConfigStepResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerOperationalHistoryEntry) DeepCopyInto(out *RunnerOperationalHistoryEntry) {
	*out = *in
	in.AppliedAt.DeepCopyInto(&out.AppliedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerOperationalHistoryEntry.
func (in *RunnerOperationalHistoryEntry) DeepCopy() *RunnerOperationalHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(RunnerOperationalHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerPhaseConfig) DeepCopyInto(out *RunnerPhaseConfig) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerPhaseConfig.
func (in *RunnerPhaseConfig) DeepCopy() *RunnerPhaseConfig {
	if in == nil {
		return nil
	}
	out := new(RunnerPhaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembership) DeepCopyInto(out *SeamMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembership.
func (in *SeamMembership) DeepCopy() *SeamMembership {
	if in == nil {
		return nil
	}
	out := new(SeamMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipList) DeepCopyInto(out *SeamMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeamMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipList.
func (in *SeamMembershipList) DeepCopy() *SeamMembershipList {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipSpec) DeepCopyInto(out *SeamMembershipSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipSpec.
func (in *SeamMembershipSpec) DeepCopy() *SeamMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipStatus) DeepCopyInto(out *SeamMembershipStatus) {
	*out = *in
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipStatus.
func (in *SeamMembershipStatus) DeepCopy() *SeamMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterOperationFailureReason) DeepCopyInto(out *TalosClusterOperationFailureReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterOperationFailureReason.
func (in *TalosClusterOperationFailureReason) DeepCopy() *TalosClusterOperationFailureReason {
	if in == nil {
		return nil
	}
	out := new(TalosClusterOperationFailureReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterOperationRecord) DeepCopyInto(out *TalosClusterOperationRecord) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(TalosClusterOperationFailureReason)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterOperationRecord.
func (in *TalosClusterOperationRecord) DeepCopy() *TalosClusterOperationRecord {
	if in == nil {
		return nil
	}
	out := new(TalosClusterOperationRecord)
	in.DeepCopyInto(out)
	return out
}
