//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescendantEntry) DeepCopyInto(out *DescendantEntry) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescendantEntry.
func (in *DescendantEntry) DeepCopy() *DescendantEntry {
	if in == nil {
		return nil
	}
	out := new(DescendantEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndex) DeepCopyInto(out *InfrastructureLineageIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndex.
func (in *InfrastructureLineageIndex) DeepCopy() *InfrastructureLineageIndex {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureLineageIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexList) DeepCopyInto(out *InfrastructureLineageIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructureLineageIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexList.
func (in *InfrastructureLineageIndexList) DeepCopy() *InfrastructureLineageIndexList {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureLineageIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexRootBinding) DeepCopyInto(out *InfrastructureLineageIndexRootBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexRootBinding.
func (in *InfrastructureLineageIndexRootBinding) DeepCopy() *InfrastructureLineageIndexRootBinding {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexRootBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexSpec) DeepCopyInto(out *InfrastructureLineageIndexSpec) {
	*out = *in
	out.RootBinding = in.RootBinding
	if in.DescendantRegistry != nil {
		in, out := &in.DescendantRegistry, &out.DescendantRegistry
		*out = make([]DescendantEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyBindingStatus != nil {
		in, out := &in.PolicyBindingStatus, &out.PolicyBindingStatus
		*out = new(InfrastructurePolicyBindingStatus)
		**out = **in
	}
	if in.OutcomeRegistry != nil {
		in, out := &in.OutcomeRegistry, &out.OutcomeRegistry
		*out = make([]OutcomeEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(LineageRetentionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexSpec.
func (in *InfrastructureLineageIndexSpec) DeepCopy() *InfrastructureLineageIndexSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexStatus) DeepCopyInto(out *InfrastructureLineageIndexStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexStatus.
func (in *InfrastructureLineageIndexStatus) DeepCopy() *InfrastructureLineageIndexStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePolicyBindingStatus) DeepCopyInto(out *InfrastructurePolicyBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePolicyBindingStatus.
func (in *InfrastructurePolicyBindingStatus) DeepCopy() *InfrastructurePolicyBindingStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePolicyBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRetentionPolicy) DeepCopyInto(out *LineageRetentionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRetentionPolicy.
func (in *LineageRetentionPolicy) DeepCopy() *LineageRetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(LineageRetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutcomeEntry) DeepCopyInto(out *OutcomeEntry) {
	*out = *in
	in.OutcomeTimestamp.DeepCopyInto(&out.OutcomeTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutcomeEntry.
func (in *OutcomeEntry) DeepCopy() *OutcomeEntry {
	if in == nil {
		return nil
	}
	out := new(OutcomeEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationArtifact) DeepCopyInto(out *PackOperationArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationArtifact.
func (in *PackOperationArtifact) DeepCopy() *PackOperationArtifact {
	if in == nil {
		return nil
	}
	out := new(PackOperationArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationDeployedResource) DeepCopyInto(out *PackOperationDeployedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationDeployedResource.
func (in *PackOperationDeployedResource) DeepCopy() *PackOperationDeployedResource {
	if in == nil {
		return nil
	}
	out := new(PackOperationDeployedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationFailureReason) DeepCopyInto(out *PackOperationFailureReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationFailureReason.
func (in *PackOperationFailureReason) DeepCopy() *PackOperationFailureReason {
	if in == nil {
		return nil
	}
	out := new(PackOperationFailureReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationResult) DeepCopyInto(out *PackOperationResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationResult.
func (in *PackOperationResult) DeepCopy() *PackOperationResult {
	if in == nil {
		return nil
	}
	out := new(PackOperationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackOperationResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationResultList) DeepCopyInto(out *PackOperationResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PackOperationResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationResultList.
func (in *PackOperationResultList) DeepCopy() *PackOperationResultList {
	if in == nil {
		return nil
	}
	out := new(PackOperationResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackOperationResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationResultSpec) DeepCopyInto(out *PackOperationResultSpec) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(PackOperationFailureReason)
		**out = **in
	}
	if in.DeployedResources != nil {
		in, out := &in.DeployedResources, &out.DeployedResources
		*out = make([]PackOperationDeployedResource, len(*in))
		copy(*out, *in)
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]PackOperationArtifact, len(*in))
		copy(*out, *in)
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]PackOperationStepResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationResultSpec.
func (in *PackOperationResultSpec) DeepCopy() *PackOperationResultSpec {
	if in == nil {
		return nil
	}
	out := new(PackOperationResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationResultStatus) DeepCopyInto(out *PackOperationResultStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationResultStatus.
func (in *PackOperationResultStatus) DeepCopy() *PackOperationResultStatus {
	if in == nil {
		return nil
	}
	out := new(PackOperationResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackOperationStepResult) DeepCopyInto(out *PackOperationStepResult) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackOperationStepResult.
func (in *PackOperationStepResult) DeepCopy() *PackOperationStepResult {
	if in == nil {
		return nil
	}
	out := new(PackOperationStepResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembership) DeepCopyInto(out *SeamMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembership.
func (in *SeamMembership) DeepCopy() *SeamMembership {
	if in == nil {
		return nil
	}
	out := new(SeamMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipList) DeepCopyInto(out *SeamMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeamMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipList.
func (in *SeamMembershipList) DeepCopy() *SeamMembershipList {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipSpec) DeepCopyInto(out *SeamMembershipSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipSpec.
func (in *SeamMembershipSpec) DeepCopy() *SeamMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipStatus) DeepCopyInto(out *SeamMembershipStatus) {
	*out = *in
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipStatus.
func (in *SeamMembershipStatus) DeepCopy() *SeamMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipStatus)
	in.DeepCopyInto(out)
	return out
}
