//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescendantEntry) DeepCopyInto(out *DescendantEntry) {
	*out = *in
	if in.RecordedAt != nil {
		in, out := &in.RecordedAt, &out.RecordedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescendantEntry.
func (in *DescendantEntry) DeepCopy() *DescendantEntry {
	if in == nil {
		return nil
	}
	out := new(DescendantEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndex) DeepCopyInto(out *InfrastructureLineageIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndex.
func (in *InfrastructureLineageIndex) DeepCopy() *InfrastructureLineageIndex {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureLineageIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexList) DeepCopyInto(out *InfrastructureLineageIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructureLineageIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexList.
func (in *InfrastructureLineageIndexList) DeepCopy() *InfrastructureLineageIndexList {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureLineageIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexRootBinding) DeepCopyInto(out *InfrastructureLineageIndexRootBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexRootBinding.
func (in *InfrastructureLineageIndexRootBinding) DeepCopy() *InfrastructureLineageIndexRootBinding {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexRootBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexSpec) DeepCopyInto(out *InfrastructureLineageIndexSpec) {
	*out = *in
	out.RootBinding = in.RootBinding
	if in.DescendantRegistry != nil {
		in, out := &in.DescendantRegistry, &out.DescendantRegistry
		*out = make([]DescendantEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyBindingStatus != nil {
		in, out := &in.PolicyBindingStatus, &out.PolicyBindingStatus
		*out = new(InfrastructurePolicyBindingStatus)
		**out = **in
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(LineageRetentionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexSpec.
func (in *InfrastructureLineageIndexSpec) DeepCopy() *InfrastructureLineageIndexSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureLineageIndexStatus) DeepCopyInto(out *InfrastructureLineageIndexStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureLineageIndexStatus.
func (in *InfrastructureLineageIndexStatus) DeepCopy() *InfrastructureLineageIndexStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureLineageIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePolicyBindingStatus) DeepCopyInto(out *InfrastructurePolicyBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePolicyBindingStatus.
func (in *InfrastructurePolicyBindingStatus) DeepCopy() *InfrastructurePolicyBindingStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePolicyBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRetentionPolicy) DeepCopyInto(out *LineageRetentionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRetentionPolicy.
func (in *LineageRetentionPolicy) DeepCopy() *LineageRetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(LineageRetentionPolicy)
	in.DeepCopyInto(out)
	return out
}
